### ISSUE TITLE
Provider interactions failing when verifying body

### ISSUE THREAD

**Issue by AshleyPoole** [bartschotten/com-pact#13]
Verifying interactions that check the body of the response seem to be failing when using .NET 3.1. Below is an exception from the test, that states the test passed, but then also failed. Debugging and stepping through, does show that the provider (controller) is returning this data during the test.

```
ComPact.Exceptions.PactVerificationException : A get request for data (passed)
A get request for data (failed):
- Property 'Id' was not present in the actual response.
- Property 'SomeInt' was not present in the actual response.
   at ComPact.Verifier.PactVerifier.VerifyPactAsync(String path)
   at DataApi.PactTests.ConsumerContractTests.VerifyInteractionWithClient() in C:\temp\Com-Pact-Demo\DataApi.PactTests\ContractConsumerTests.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
```

I've put up an example project here which demostrates the issue: https://github.com/AshleyPoole/Com-Pact-Demo

The DataApi.PactTests (provider) are failing with the above exception. Tests that don't verify the body seem to pass.

**Comment by bartschotten** [comment]
Ah, there is actually an official testcase for it, which had already been included in ComPact as well: https://github.com/pact-foundation/pact-specification/blob/version-2/testcases/response/body/property%20name%20is%20different%20case.json
Property names should indeed be case sensitive.

**Comment by AshleyPoole** [comment]
Maybe Compact could allow consumers to specify the Json serializer settings similar to PactBuilder class in Pact.Net project?
https://github.com/pact-foundation/pact-net/blob/d0c95d68f39d5a4b8833076f4cf576c41a799c04/PactNet/PactBuilder.cs#L20

**Comment by bartschotten** [comment]
Unless it solves a concrete problem I'm hesitant to add more configuration options, since it also means  more scenarios to test.
