### ISSUE TITLE
Strings formatted as ISO datetimes get deserialized to DateTime instead of string

### ISSUE THREAD

**Issue by bartschotten** [bartschotten/com-pact#14]
Serialization on producer creates json string with "mydate":"2020-04-01T00:00:00"
But when string deserialized back to object it will be DateTime mydate, so it will fail on type compare.
We can not change the deserialization , since it is hidden.
So, its not so clear for me, how to manage it from produce side.
The only way i see it by changing the contract from:
`"$.ToDateUtc": {
            "matchers": [
              {
                "match": "regex",
                "regex": "(\\d+)(?:-(\\d+))?"
              }
            ]
          }`

to:
```
$.ToDateUtc": {
            "matchers": [
              {
                "match": "type"
              }
            ]
          }
```
In such case i will lose the regex validation but this is ok becouse it will try to serialize the string to DateTime and if string is not valid then it will fail.

_Originally posted by @sfiodorov in https://github.com/bartschotten/com-pact/issues/9#issuecomment-638860403_

**Comment by bartschotten** [comment]
This is apparently a known issue with Newtonsoft JSON: https://github.com/JamesNK/Newtonsoft.Json/issues/862

**Comment by sfiodorov** [comment]
@bartschotten :
Thanks for openning this issue.
It looks like NewtonsoftJson will not change this behavor.
What do you think about passing DateParseHandling.None at serialization config, or, at least, to allow to client code to pass serialization configuration as parmater with your default if null?

**Comment by bartschotten** [comment]
I've tried that, but apparently it doesn't work on JToken.Parse or JToken.FromObject (this is also mentioned somewhere in that discussion). I'm looking at a different way to convert to JToken now.

**Comment by eNeRGy164** [comment]
Did you try https://github.com/JamesNK/Newtonsoft.Json/issues/862#issuecomment-225007421 ?

**Comment by bartschotten** [comment]
Working on it :)

**Comment by sfiodorov** [comment]
@bartschotten : looks like it works as expected at version 0.4.0
Thanks!

**Comment by sfiodorov** [comment]
@bartschotten 
Hey. It looks like we are facing similar issue with boolean.
Assuming i have in pact:
```
  "$.Test": {
            "matchers": [
              {
                "match": "regex",
                "regex": "^([Tt]rue|[Ff]alse)$"
              }
            ]
          }
```
And on message:
`"Test":"False"`
At BodyMatcher:CompareExpectedTokenWithActual i see that
expectedToken.Type is String but actualToken.Type is boolean.

Any idea how to make it to deserialize as string?
