### ISSUE TITLE
Support asynchronous MessageBuilder VerifyConsumer

### ISSUE THREAD

**Issue by sfiodorov** [bartschotten/com-pact#17]
Hi @bartschotten .
What do you think about MessageBuilder:VerifyConsumer that supports async pattern?
Most of our calls to consumers are async
It will be nice to have additional 
`MessageBuilder VerifyConsumerAsync<T>(Func<Task,T> messageHandler)`
Together with `MessageBuilder:VerifyConsumerAsync<T>`
Currently, im using Task.Wait/Task.Result inside the VerifyConsumer and async pattern will fit better.

**Comment by bartschotten** [comment]
Sounds like a great improvement. Feel like making a PR?

**Comment by sfiodorov** [comment]
@bartschotten , will try do that .

**Comment by sfiodorov** [comment]
@bartschotten : 
Here is my proposal:
https://github.com/bartschotten/com-pact/pull/19

**Comment by sfiodorov** [comment]
merged
