### ISSUE TITLE
Error message renders type instead of any relevant value

### ISSUE THREAD

**Issue by eNeRGy164** [bartschotten/com-pact#2]
When setting the provider state failes, the exception message is
```
Could not set providerState 'System.Collections.Generic.List`1[ComPact.Models.ProviderState]'.
Got a NotFound response.
```

``System.Collections.Generic.List`1[ComPact.Models.ProviderState]`` is not very helpful here.

Source: https://github.com/bartschotten/com-pact/blob/83e3c2d3d49d05b6b85760a63cfa9d6a367750ec/ComPact/Verifier/PactVerifier.cs#L159

**Comment by bartschotten** [comment]
Solved by c5b066f72f095b6e35bb4e8dd99e1502a168f969
