### ISSUE TITLE
Strings like "true"/"false" get deserialized to DateTime instead of string

### ISSUE THREAD

**Issue by sfiodorov** [bartschotten/com-pact#20]
Hey.
Issue similar to https://github.com/bartschotten/com-pact/issues/14
Pact:
```
"$.Test": {
            "matchers": [
              {
                "match": "regex",
                "regex": "^([Tt]rue|[Ff]alse)$"
              }
            ]
          }
```

Message:
```
{
"Test":"False"
}
```
BodyMatcher:CompareExpectedTokenWithActual throws, becouse expected type is string and actual is Boolean.
Think it comes from seriazier that forces the type of "True" to be boolean.

**Comment by bartschotten** [comment]
I can only reproduce this when the body in the Pact is `{ "Test":true }` and the body in the actual message is `{ "Test":"false" }`.
In that case it is expected behaviour because the types don't match.
Either just use booleans, in which case you don't need the regex, or use strings in both the pact and the actual message.

**Comment by sfiodorov** [comment]
@bartschotten 
Thanks, but how do i describe boolean in pact definition? There is no Some.Boolean

**Comment by bartschotten** [comment]
You can just use Some.Element. Booleans do not really have a specific meaning in Pact so there was no need to create a specific method for it, but I can see why it may be a bit confusing.

**Comment by sfiodorov** [comment]
@bartschotten , but how do i ensure that values are only true/false ? 
Some.Element.Named("BooleanProperty").Like(true) ?

**Comment by bartschotten** [comment]
Exactly. That will automatically result in a Type matching rule.

**Comment by sfiodorov** [comment]
Nice! Thanks. Now i understand the point .
