### ISSUE TITLE
Question: Work with matchers in content

### ISSUE THREAD

**Issue by Kampfmoehre** [bartschotten/com-pact#22]
I am trying to set up Pact for AMQP messages between a .NET provider and a NodeJS consumer. On the Node side the library [PactJS](https://github.com/pact-foundation/pact-js) is used, one the .NET side I am using this awesome library.

I have successfully make that work with a plain object, however I am struggling to make it work with matchers. I have tried the latest beta version with their new MatcherV3 API which is generating a json pact file that looks like this:
```json
{
  "consumer": {
    "name": "NodeSide"
  },
  "provider": {
    "name": "NetSide"
  },
  "messages": [
    {
      "description": "a password reset mail",
      "providerStates": [],
      "contents": {
        "type": "mail:send",
        "props": {
          "profile": "PASSWORD_RESET",
          "from": {
            "pact:matcher:type": "type",
            "value": "noreply@someone.de"
          },
          "to": {
            "pact:matcher:type": "type",
            "value": "someone.needs@password.com"
          },
          "subject": "Password reset",
          "resetUrl": {
            "pact:matcher:type": "type",
            "value": "https://reset.your.password"
          }
        }
      },
      "matchingRules": {},
      "metaData": {
        "correlationId": "some-string",
        "type": "mail:send",
        "appId": "app:pact-test",
        "contentType": "application/json"
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    }
  }
}
```

When I try to validate the .NET provider against this, ComPact is treating the values literally, meaning it is complaining that for example the reference object has no `props.from.pact:matcher:type` property but expected one.

For reference here is the plain object without matchers that is working:
```json
{
  "consumer": {
    "name": "NodeSide"
  },
  "provider": {
    "name": "NetSide"
  },
  "messages": [
    {
      "description": "a password reset mail",
      "providerStates": [],
      "contents": {
        "type": "mail:send",
        "props": {
          "profile": "PASSWORD_RESET",
          "from": "noreply@someone.de",
          "to": "someone.needs@password.com",
          "subject": "Password reset",
          "resetUrl": "https://reset.your.password"
        }
      },
      "matchingRules": {
      },
      "metaData": {
        "correlationId": "some-string",
        "type": "mail:send",
        "appId": "app:pact-test",
        "contentType": "application/json"
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    }
  }
}
```
My first guess was, that the Node side is somewhat broken and those rules should be in `matchingRules` instead. I asked if there is any way to make the matchers appear in `matchingRules` instead - since when I manually move the matchers to the `matchingRules` object it kinda works. (For reference: https://github.com/pact-foundation/pact-js/issues/615)

However they indicated that instead this library is not compliant to the Pact spec. So I am asking here, should the above work and the problem is somewhere else? Can I make the above json work with Compact?
Thank you.

**Comment by bartschotten** [comment]
I can't believe it took me so long to respond to this...
I can't find the way they are doing matchingRules anywhere in the spec, but maybe I'm looking in the wrong place. If there's an official specification I'm all for implementing it in ComPact.

**Comment by Kampfmoehre** [comment]
Since some time passed since I created this issue things seem to have changed since then. I generated a pact file with the current beta of the PactJS library and the matchers are now put in the matchingRules property. This seems to work fine with ComPact so I am going to close this issue. If I encounter any problems I will open a new one.
